FROM arm64v8/alpine

RUN apk add --no-cache  --update nodejs-current npm curl bash procps tzdata
RUN node --version
RUN npm --version

ENV TZ="America/New_York"

#RUN apt-get update -y && apt-get install -y apt-utils tzdata && apt-get install fswebcam ffmpeg -y && apt-get install mpg123 -y && apt-get install vim -y

WORKDIR /server

COPY . /server

RUN npm install -g npm
RUN npm install
RUN npm run build

VOLUME /mms_shared_volume
EXPOSE 3000
CMD [ "npm", "start" ]